title: Cryptoverse
author: Hodler
email: Harnish@harnish.com
description: > Hey Son, welcome to my blog 
  News and discussions about Blockchain, Cryptocurrency, Climatechange and whatever we dig.

# social links
twitter_username: hohoharnish # DO NOT include the @ character, or else the build will fail!
github_username:  cyberstupid # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
